[package]
name = "ukweli_db"
version = "0.1.0"
edition = "2024"

[dependencies]
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
rand = "0.8.5"
sha256 = "1.6.0"
thiserror = "2.0.17"
serde_json = "1.0"
